### ISSUE TITLE
Integrate with developer portal

### ISSUE THREAD

**Issue by stefanbschneider** [sonata-nfv/tng-sdk-project#54]
- [x] Draft mockups for developer portal using the tng-sdk-project microservice
- [x] Identify required REST calls for all buttons and GUI elements
- [x] Identify required REST response data for filling overview elements
- [ ] Adjust REST API as required
  - [ ] Endpoint for accessing, updating, deleting individual files of a project
  - [ ] Endpoint for updating project metadata (in manifest) with PUT
  - [ ] Return summarized project status in response to GET to `/projects/uuid`

**Comment by StefanUPB** [comment]
I sketched some initial mockups for the developer portal:

![developer portal mockup sketches-1](https://user-images.githubusercontent.com/28340802/48256354-9b8ab000-e40f-11e8-8a53-002978c16c98.png)
![developer portal mockup sketches-2](https://user-images.githubusercontent.com/28340802/48256361-a04f6400-e40f-11e8-8670-e82757fea3e1.png)

I'll try to draw a bit nicer version with draw.io. I will also check which buttons should correspond to which REST calls on the backend to the SDK microservices.

@anapolg Could you have a look at the mockups and let me know what you think? Regarding the implementation, I guess, the existing tng-portal makes sense or would you rather create a separate repo?

**Comment by StefanUPB** [comment]
Here are some nicer drawings of the mockups with draw.io: 

![mockups-descriptor generation](https://user-images.githubusercontent.com/28340802/48258415-579aa980-e415-11e8-99a5-a2ef5609f109.png)
![mockups-descriptor review edit](https://user-images.githubusercontent.com/28340802/48258417-579aa980-e415-11e8-873b-61aee29ba328.png)
![mockups-project](https://user-images.githubusercontent.com/28340802/48258419-58334000-e415-11e8-8d34-5399a42a424f.png)
![mockups-validate](https://user-images.githubusercontent.com/28340802/48258414-579aa980-e415-11e8-9470-70f2c67b860b.png)
![mockups-package](https://user-images.githubusercontent.com/28340802/48258418-579aa980-e415-11e8-9f49-54d9d8450ab3.png)

If we agree in which repo to do the portal development, we can move the issue there and also create a wiki page with the Mockups etc for better overview. I'll also provide the source files for these mockups if that helps.

**Comment by StefanUPB** [comment]
I created a wiki page with the mockups and required interactions with the REST API of the SDK services here: https://github.com/sonata-nfv/tng-portal/wiki/UPD-workflow-mockups

It still contains a number of todos that also affect the SDK side (e.g., missing REST endpoints or required fields in a response).

**Comment by StefanUPB** [comment]
Related user story: https://git.cs.upb.de/5gtango/UserStories/issues/456

**Comment by stefanbschneider** [comment]
Corresponding development and issues are maintained here: https://github.com/sonata-nfv/tng-portal/projects/2
