### ISSUE TITLE
tng-sdk-validate fails because of tng-sdk-project change

### ISSUE THREAD

**Issue by mpeuster** [sonata-nfv/tng-sdk-project#58]
Reported by @anapolg:

A validation `tng-validate -i --project misc/5gtango_ns_project_example1/`

gives

```
Syntax and integrity validation
Traceback (most recent call last):
  File "/Users/manuel/tango/venv_tango_sdk/bin/tng-validate", line 11, in <module>
    load_entry_point('tngsdk.validate', 'console_scripts', 'tng-validate')()
  File "/Users/manuel/tango/tng-sdk-validation/src/tngsdk/validation/__init__.py", line 71, in main
    result_validator = cli.dispatch(args, validator)
  File "/Users/manuel/tango/tng-sdk-validation/src/tngsdk/validation/cli.py", line 118, in dispatch
    if not validator.validate_project(args.project_path):
  File "/Users/manuel/tango/tng-sdk-validation/src/tngsdk/validation/validator.py", line 300, in validate_project
    project = Project.__create_from_descriptor__(self._workspace,
AttributeError: type object 'Project' has no attribute ‘__create_from_descriptor__’
```

Reason is the missing:

```
 @staticmethod
    def __create_from_descriptor__(workspace, prj_root, translate=False):
```

in the latest version of project.py.

**Comment by StefanUPB** [comment]
I refactored large parts of the existing code to make it easier to maintain. The function is now called [`load_project(prj_root, workspace=None, translate=False)`](https://github.com/sonata-nfv/tng-sdk-project/blob/2e0727ab27c8967c556e4f1c0a6aa4496a92c311/src/tngsdk/project/project.py#L349).

The best way would be just to update the corresponding call in the validator when using the new/current version of tng-project.

We should probably setup auto. integration tests to catch such errors earlier in the future.

**Comment by anapolg** [comment]
Solved and working the validation.
