### ISSUE TITLE
Warning when used on CLI

### ISSUE THREAD

**Issue by mpeuster** [sonata-nfv/tng-sdk-project#59]
I am integrating the validator to the packager (this means also tng-project ist called) and noticed the following:

```
tng-project -p misc/5gtango_ns_project_example1/ --status
```
(the example service is [this](https://github.com/sonata-nfv/tng-sdk-package/tree/master/misc/5gtango_ns_project_example1))

Output:
```
2018-12-07 17:56:49 mapupb tngsdk.project.project[43965] WARNING Project version 0.5 is outdated. To translate to new 5GTANGO project version use --translate
2018-12-07 17:56:49 mapupb tngsdk.project.project[43965] WARNING Couldn't retrieve the projects UUID.
```

This is a bit strange:

1. Even if I set the version of the project.yaml to 0.6, it gives the same error but with `0.6`. That seems wrong. `0.5`is the latest version according to the wiki, no? Maybe tng-project can not handle versions given as string, so the `<` fails? But it should be able to handle them. 

2. The UUID warning is strange. Why should someone have a UUID for a local project? I guess this comes from the REST extension?

These problems **are non blocking**. But would be nice if this would be fixed at some point.

**Comment by StefanUPB** [comment]
Thanks, I'll have a look! 

Yes, the UUID thing is for the REST extension - I think for any new projects that are now generated, a UUID field is automatically generated that is used within the REST backend to reference and organize projects. Maybe I can disable that warning when using the CLI.

Not sure about the issue with the version number, but I'll look into it.

**Comment by mpeuster** [comment]
Ah good point. Maybe we can just add a new UUID and store it if someone opens an old project without an UUID? We have many old projects in old gits. I guess it would be handy, and no one would notice.
