### ISSUE TITLE
Create functions: get_slad, get_rpd and get_sliced

### ISSUE THREAD

**Issue by MiguelRivasQuobis** [sonata-nfv/tng-sdk-project#85]
Similar to how the project module provides a method `get_nsds` and `get_vnfds`, it should also provide a method `get_slad`, `get_rpd` and `get_sliced` to return all included test descriptors based on their MIME type 

- Slad -> SLA descriptor
- RPD -> Runtime policy descriptors
- Sliced -> Slice descriptor

**Comment by stefanbschneider** [comment]
I added MIME types for these descriptors here: https://github.com/sonata-nfv/tng-schema/wiki/PkgSpec_LATEST#5gtango-specific-mime-types

Not sure if this also affects the packager? @mpeuster

**Comment by stefanbschneider** [comment]
@MiguelRivasQuobis For consistent naming with the previous functions and the MIME types, I now implemented the functions with these names:

* `get_slads()`
* `get_rpds()`
* `get_nstds()`
