### ISSUE TITLE
REST: Return descriptor file endpoints when creating a new project

### ISSUE THREAD

**Issue by stefanbschneider** [sonata-nfv/tng-sdk-project#88]
After completing the endpoints for accessing files within a project (issue #83 ), this is the next step:

When creating a new project with generated descriptors (POST to `/projects`), extend the return to additionally include an array of file names and their endpoints for accessing the files. For example:

```
# request: new project with 2 VNFDs
$ curl -X POST localhost:5098/api/v1/projects  -d vnfs=2

# JSON response
{
  uuid: kölafjölskafjdöaskfdö,
  error_msg: None,
  files: [
    tango_vnfd0.yml: 'http://127.0.0.1:5098/api/v1/projects/kölafjölskafjdöaskfdö/tango_vnfd0.yml',
    tango_vnfd1.yml: 'http://127.0.0.1:5098/api/v1/projects/kölafjölskafjdöaskfdö/tango_vnfd1.yml',
    tango_nsd.yml: 'http://127.0.0.1:5098/api/v1/projects/kölafjölskafjdöaskfdö/tango_nsd.yml'
  ]
}
```

For that you'll have to use the newly developed endpoints from #83 and extend the return of the POST [here](https://github.com/zulfiqarjunejo/tng-sdk-project/blob/master/src/tngsdk/rest.py#L203), which also requires updating the response model [here](https://github.com/zulfiqarjunejo/tng-sdk-project/blob/master/src/tngsdk/rest.py#L126).

**Comment by zulfiqarjunejo** [comment]
My observation is that we do not need to return filename and the access point separately, just return a list of file access points.
