### ISSUE TITLE
Validation error with example project

### ISSUE THREAD

**Issue by stefanbschneider** [sonata-nfv/tng-sdk-project#99]
I'm getting an validation error that I don't understand when running 

```
tng-validation --project example-project 
```

on the example project defined in the tng-sdk-project repo: https://github.com/sonata-nfv/tng-sdk-project/tree/master/example-project

The error is

```
2019-08-16 14:44:39 nb-stschn tango.validator.events:l50 ERROR Undefined connection point
2019-08-16 14:44:39 nb-stschn tango.validator.events:l64 ERROR Function descriptor (VNFD) of vnf_id='vnf1' declared in connection point 'vnf1' in virtual link 'input' is not defined
```

I don't get what the error message is referring to. there is no connection point vnf1 referenced in the vnfd: https://github.com/sonata-nfv/tng-sdk-project/blob/master/example-project/tango_vnfd0.yml
I also don't see any other issue with the descriptor

Not sure, who's currently working on the validator and could help me out with this? @MiguelRivasQuobis @anapolg

**Comment by anapolg** [comment]
Hi @stefanbschneider one question:

How do you define virtual links between vnf1 and vnf2 in `tango_nsd` when you only have one function defined in the service which is `vnf0`? Am I missing something in there?

**Comment by stefanbschneider** [comment]
You're right, the thing with the VNFs in the NSD is weird - I'll have a look! Thanks for the hint
